### ISSUE TITLE
opensource hardware

### ISSUE THREAD

**Issue by char32** [SoloKeysSec/solo#41]
Hey,
is there a plan to opensource the hardware too like with the U2FZero? The main page states "easy to solder hardware" but I mean does it include gerbers, KiKad, etc.? I enjoyed that with the U2Fzero.
In the meantime I'll start to get a nucleo board :-)

Thanks!

- char32

**Comment by conorpp** [comment]
Yup, I plan to open source the hardware soon, at least before Kickstarter orders are delivered.  First revision will be same as what we manufactured.  Uses QFN32 package and a fine pitch 4 pin part, so not quite as easy to solder as U2FZero for now, but it's pretty doable with a stencil and hot air.

**Comment by craftyguy** [comment]
Any update on this?

**Comment by conorpp** [comment]
Shipping and holidays delayed me, but I just open sourced it here:
https://github.com/SoloKeysSec/solo-hw

Sorry for delay!
