### ISSUE TITLE
购买后只有订单没有确认邮件!!!

### ISSUE THREAD

**Issue by kongkonga** [SoloKeysSec/solo#43]
https://solokeys.com/preorder/购买了solo tap。网页只给了我一个订单号，我一直没有收到确认邮件。
Your order number is #103094185. You'll receive an e-mail confirmation shortly for your records.

**Comment by nickray** [comment]
Hi @kongkonga 
For order-related questions, please contact hello@solokeys.com, this repository is for software-related issues. I have checked your order though, it is in our system and marked as paid. Currently we are finishing fulfilment of the non-US orders, after that we will start fulfilling the preorders. Thanks for your order!
