### ISSUE TITLE
Port to SAM L11

### ISSUE THREAD

**Issue by conorpp** [SoloKeysSec/solo#6]

**Comment by ohazi** [comment]
SAM L11 doesn't have a USB peripheral... is that not a showstopper?

**Comment by conorpp** [comment]
We are using the EFM8UB1 chip to implement the USB HID interface.  Current schematic:
![](https://i.imgur.com/sVQ34em.png)

**Comment by nickray** [comment]
rip SAM L11, may you possible rise again in the future
